server:
  port: 8081 # Puerto en el que correr� este microservicio

spring:
  application:
    name: servicio-rutas # Nombre del servicio que se registrar� en Eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL del Eureka Server