server:
  port: 8082  # Este microservicio correrá en el puerto 8082.

spring:
  application:
    name: servicio-buses  # Nombre del servicio que se registrará en Eureka.

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Dirección del Eureka Server.
